### ISSUE TITLE
Freyja variants invalid option -- 'r'

### ISSUE THREAD

**Issue by jacqgg** [andersen-lab/Freyja#70] opened 2022-07-14 12:39 UTC
Hi,
I'm trying to run Freyja on bam file (aligned reads to covid reference, with trimmed primers - bam file after artic-ncov2019 pipeline):
```
freyja variants --variants "var_output" --depths "var_depth_output" --ref "nCoV-2019.reference.fasta" "primertrimmed.rg.sorted.bam"
```
and I always get error info _"ivar: invalid option -- 'r' "_. The same error is when running freyja variants without options like --variants, --depths or even --ref, so it is probably not the freyja arguments problem...

this topic: https://unix.stackexchange.com/questions/555360/bash-cat-invalid-option-r resolving similar problem with cat command, where cat is interpreting -rsomething like an additional argument '-r'. The problem was resolved by ending arguments section with standalone " -- ". Maybe here I have similar problem, but how to edit iVar command running by Freya?
[Freyja version 1.3.8, iVar version 1.0]

**Comment by joshuailevy** [comment] 2022-07-15 23:44
I'm not sure what's going on here, but there shouldn't be quotation marks around filenames used in your command. Can you post the whole command as well as any additional outputs/errors that are produced when you run it? Will help me diagnose what's going on. Thanks!

**Comment by jacqgg** [comment] 2022-07-18 12:41
that's all, unfortunately. The only output is above and the command looks the same as in my first post (but without quotations). The environments is from clear conda installation

**Comment by joshuailevy** [comment] 2022-07-18 16:19
Unfortunately I haven't been able to reproduce this error. What sort of operating system are you using? I've tested extensively on mac/linux machines, but it's possible that things could be behaving weirdly on windows, for example.

**Comment by joshuailevy** [comment] 2022-07-20 06:34
Hm... I'd be happy to take a look at your bam file to try to investigate further if you're up for sharing it.

**Comment by jacqgg** [comment] 2022-07-20 08:05
Sure:
- bam file [https://drive.google.com/file/d/1snC_vUT-8FSQDkEeQ46roRBzMYDaDuzg/view?usp=sharing](url)
- reference [https://drive.google.com/file/d/1fJJLw-tW7HZ9ZKThZv6lLYH3sAJllw8I/view?usp=sharing](url)

**Comment by joshuailevy** [comment] 2022-07-25 06:03
Sorry for the delay. I just ran the following command it seems to have worked just fine: 
```freyja variants BC22.primertrimmed.rg.sorted.bam --variants test.tsv --depths test.depth --ref nCoV-2019.reference.fasta``` 

Perhaps there's an issue with your installation of freyja and/or ivar?

**Comment by joshuailevy** [comment] 2022-08-01 18:54
Any luck getting freyja to run on your samples? Going to close this since there hasn't been much activity here and it seems to be more of a freyja/ivar installation issue.

**Closed by joshuailevy** 2022-08-01 18:54 UTC
